[package]
name = "rules-rust-bazel-7-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libffi = "3.2.0"
